// Arc IR → JavaScript Code Generator

import { IRModule, IRBlock, IRInstr, IRFunction } from "./ir.js";

export function generateJS(module: IRModule): string {
  const lines: string[] = [];
  lines.push("// Generated by Arc Compiler");
  lines.push("");

  // Runtime helpers
  lines.push(`// Arc Runtime`);
  lines.push(`const __arc_runtime = {`);
  lines.push(`  len(a) { return Array.isArray(a) ? a.length : typeof a === "string" ? a.length : 0; },`);
  lines.push(`  str(v) { return String(v); },`);
  lines.push(`  push(arr, v) { arr.push(v); return arr; },`);
  lines.push(`  __toStr(v) { if (v === null) return "nil"; if (typeof v === "boolean") return v ? "true" : "false"; if (typeof v === "number" || typeof v === "string") return String(v); if (Array.isArray(v)) return "[" + v.map(x => this.__toStr(x)).join(", ") + "]"; if (v && v.__map) { const entries = [...v.entries.entries()].map(([k, val]) => k + ": " + this.__toStr(val)); return "{" + entries.join(", ") + "}"; } return String(v); },`);
  lines.push(`  print(v) { console.log(this.__toStr(v)); },`);
  lines.push(`  println(v) { console.log(this.__toStr(v)); },`);
  lines.push(`  head(a) { return a[0]; },`);
  lines.push(`  tail(a) { return a.slice(1); },`);
  lines.push(`  map(a, f) { return a.map(f); },`);
  lines.push(`  filter(a, f) { return a.filter(f); },`);
  lines.push(`  fold(a, init, f) { return a.reduce((acc, x) => f(acc, x), init); },`);
  lines.push(`  range(start, end) { const r = []; for (let i = start; i < end; i++) r.push(i); return r; },`);
  lines.push(`  keys(m) { return m && m.__map ? Array.from(m.entries.keys()) : Object.keys(m || {}); },`);
  lines.push(`  values(m) { return m && m.__map ? Array.from(m.entries.values()) : Object.values(m || {}); },`);
  lines.push(`  type(v) { if (v === null) return "nil"; if (Array.isArray(v)) return "list"; return typeof v; },`);
  lines.push(`  abs(n) { return Math.abs(n); },`);
  lines.push(`  max(a, b) { return Math.max(a, b); },`);
  lines.push(`  min(a, b) { return Math.min(a, b); },`);
  lines.push(`  floor(n) { return Math.floor(n); },`);
  lines.push(`  ceil(n) { return Math.ceil(n); },`);
  lines.push(`  round(n) { return Math.round(n); },`);
  lines.push(`  sort(a) { return [...a].sort((x,y) => x < y ? -1 : x > y ? 1 : 0); },`);
  lines.push(`  reverse(a) { return [...a].reverse(); },`);
  lines.push(`  contains(a, v) { return Array.isArray(a) ? a.includes(v) : typeof a === "string" ? a.includes(v) : false; },`);
  lines.push(`  join(a, sep) { return a.join(sep); },`);
  lines.push(`  split(s, sep) { return s.split(sep); },`);
  lines.push(`  trim(s) { return s.trim(); },`);
  lines.push(`  replace(s, old, nw) { return s.replaceAll(old, nw); },`);
  lines.push(`  uppercase(s) { return s.toUpperCase(); },`);
  lines.push(`  lowercase(s) { return s.toLowerCase(); },`);
  lines.push(`  upper(s) { return s.toUpperCase(); },`);
  lines.push(`  lower(s) { return s.toLowerCase(); },`);
  lines.push(`  type_of(v) { if (v === null) return "nil"; if (typeof v === "boolean") return "bool"; if (typeof v === "number") return Number.isInteger(v) ? "int" : "float"; if (typeof v === "string") return "string"; if (Array.isArray(v)) return "list"; if (v && v.__map) return "map"; return "unknown"; },`);
  lines.push(`  sum(a) { return a.reduce((s, x) => s + x, 0); },`);
  lines.push(`  flat(a) { return a.flat(); },`);
  lines.push(`  zip(a, b) { return a.map((x, i) => [x, b[i]]); },`);
  lines.push(`  enumerate(a) { return a.map((x, i) => [i, x]); },`);
  lines.push(`  slice(a, s, e) { return a.slice(s, e); },`);
  lines.push(`  append(a, v) { return [...a, v]; },`);
  lines.push(`  concat(a, b) { return [...a, ...b]; },`);
  lines.push(`  unique(a) { return [...new Set(a)]; },`);
  lines.push(`  int(v) { return parseInt(v, 10); },`);
  lines.push(`  float(v) { return parseFloat(v); },`);
  lines.push(`  __await(v) { return v && v.__async ? v.thunk() : v; },`);
  lines.push(`  __fetch_parallel(...targets) { return targets; },`);
  lines.push(`  __make_map(keys, values) { const m = { __map: true, entries: new Map() }; for (let i = 0; i < keys.length; i++) m.entries.set(keys[i], values[i]); return m; },`);
  lines.push(`};`);
  lines.push("");

  // Emit main with hoisted functions
  lines.push("// Main");
  lines.push("(function() {");

  // Hoist function definitions inside the scope
  for (const fn of module.functions) {
    lines.push(emitFunction(fn, "  "));
    lines.push("");
  }

  for (const block of module.main) {
    lines.push(...emitBlock(block, "  "));
  }
  lines.push("})();");

  return lines.join("\n");
}

function emitFunction(fn: IRFunction, baseIndent = ""): string {
  const lines: string[] = [];
  lines.push(`${baseIndent}function ${S(fn.name)}(${fn.params.map(S).join(", ")}) {`);
  for (const block of fn.blocks) {
    lines.push(...emitBlock(block, baseIndent + "  "));
  }
  lines.push(`${baseIndent}}`);
  return lines.join("\n");
}

function emitBlock(block: IRBlock, indent: string): string[] {
  const lines: string[] = [];
  const instrs = block.instrs;

  // Split instructions into labeled sections for control flow
  interface Section {
    label: string;
    instrs: IRInstr[];
  }
  const sections: Section[] = [];
  let currentSection: Section = { label: "__start", instrs: [] };
  sections.push(currentSection);

  for (const instr of instrs) {
    if (instr.op === "label") {
      currentSection = { label: instr.name, instrs: [] };
      sections.push(currentSection);
    } else {
      currentSection.instrs.push(instr);
    }
  }

  // If no labels exist, emit linearly (simple case)
  if (sections.length === 1) {
    for (const instr of instrs) {
      lines.push(indent + emitInstr(instr));
    }
    return lines;
  }

  // Use a state-machine approach with a __pc variable and a while/switch loop
  // to properly handle branches and jumps
  const labelToIdx = new Map<string, number>();
  for (let i = 0; i < sections.length; i++) {
    labelToIdx.set(sections[i].label, i);
  }

  lines.push(`${indent}var __pc = 0;`);
  lines.push(`${indent}__control: while (true) {`);
  lines.push(`${indent}  switch (__pc) {`);

  for (let i = 0; i < sections.length; i++) {
    const section = sections[i];
    lines.push(`${indent}    case ${i}: /* ${section.label} */`);

    for (const instr of section.instrs) {
      if (instr.op === "jump") {
        const target = labelToIdx.get(instr.target);
        if (target !== undefined) {
          lines.push(`${indent}      __pc = ${target}; continue __control;`);
        }
      } else if (instr.op === "branch") {
        const ifTrue = labelToIdx.get(instr.ifTrue);
        const ifFalse = labelToIdx.get(instr.ifFalse);
        lines.push(`${indent}      if (${S(instr.cond)}) { __pc = ${ifTrue}; } else { __pc = ${ifFalse}; } continue __control;`);
      } else if (instr.op === "ret") {
        lines.push(`${indent}      ` + emitInstr(instr));
      } else {
        lines.push(`${indent}      ` + emitInstr(instr));
      }
    }

    // Fall through to next section if no jump/branch/ret at end
    const lastInstr = section.instrs[section.instrs.length - 1];
    if (!lastInstr || (lastInstr.op !== "jump" && lastInstr.op !== "branch" && lastInstr.op !== "ret")) {
      if (i + 1 < sections.length) {
        lines.push(`${indent}      __pc = ${i + 1}; continue __control;`);
      } else {
        lines.push(`${indent}      break __control;`);
      }
    }
  }

  lines.push(`${indent}    default: break __control;`);
  lines.push(`${indent}  }`);
  lines.push(`${indent}}`);

  return lines;
}

function emitInstr(instr: IRInstr): string {
  switch (instr.op) {
    case "const":
      return `var ${S(instr.dest)} = ${JSON.stringify(instr.value)};`;
    case "load":
      if (instr.name.startsWith("@fn:")) {
        return `var ${S(instr.dest)} = ${S(instr.name.slice(4))};`;
      }
      return `var ${S(instr.dest)} = ${S(instr.name)};`;
    case "store":
      if (instr.src.startsWith("@fn:")) {
        const fnName = instr.src.slice(4);
        // If storing a function reference to a variable with the same name,
        // the hoisted function definition already provides it — skip redundant var
        if (S(instr.name) === S(fnName)) {
          return `/* ${S(instr.name)} = ${S(fnName)} (hoisted) */`;
        }
        return `var ${S(instr.name)} = ${S(fnName)};`;
      }
      return `var ${S(instr.name)} = ${S(instr.src)};`;
    case "binop":
      return `var ${S(instr.dest)} = ${emitBinop(instr.operator, S(instr.left), S(instr.right))};`;
    case "unop":
      return `var ${S(instr.dest)} = ${emitUnop(instr.operator, S(instr.operand))};`;
    case "call":
      return `var ${S(instr.dest)} = ${emitCall(instr.fn, instr.args.map(S))};`;
    case "toolcall":
      return `var ${S(instr.dest)} = await fetch(${S(instr.url)}, { method: ${JSON.stringify(instr.method)}${instr.body ? `, body: JSON.stringify(${S(instr.body)})` : ""} }).then(r => r.json());`;
    case "field":
      return `var ${S(instr.dest)} = (${S(instr.obj)} == null) ? null : (${S(instr.obj)}.__map) ? ${S(instr.obj)}.entries.get(${JSON.stringify(instr.prop)}) : ${S(instr.obj)}[${JSON.stringify(instr.prop)}];`;
    case "index":
      return `var ${S(instr.dest)} = ${S(instr.obj)}[${S(instr.idx)}];`;
    case "setfield":
      return `if (${S(instr.obj)} && ${S(instr.obj)}.__map) { ${S(instr.obj)}.entries.set(${JSON.stringify(instr.prop)}, ${S(instr.src)}); } else { ${S(instr.obj)}[${JSON.stringify(instr.prop)}] = ${S(instr.src)}; }`;
    case "setindex":
      return `${S(instr.obj)}[${S(instr.idx)}] = ${S(instr.src)};`;
    case "jump":
      return `/* jump ${instr.target} */`;
    case "branch":
      return `if (${S(instr.cond)}) { /* ${instr.ifTrue} */ } /* branch */`;
    case "phi":
      return `var ${S(instr.dest)} = undefined; /* phi */`;
    case "ret":
      return instr.value ? `return ${S(instr.value)};` : "return;";
    case "list":
      return `var ${S(instr.dest)} = [${instr.elements.map(S).join(", ")}];`;
    case "map":
      return `var ${S(instr.dest)} = __arc_runtime.__make_map([${instr.keys.map(S).join(", ")}], [${instr.values.map(S).join(", ")}]);`;
    case "label":
      return `/* ${instr.name}: */`;
    case "print":
      return `__arc_runtime.print(${S(instr.value)});`;
    case "range":
      return `var ${S(instr.dest)} = __arc_runtime.range(${S(instr.start)}, ${S(instr.end)});`;
    case "nop":
      return "/* nop */";
  }
}

function emitBinop(op: string, left: string, right: string): string {
  switch (op) {
    case "++": return `String(${left}) + String(${right})`;
    case "and": return `(${left} && ${right})`;
    case "or": return `(${left} || ${right})`;
    case "==": return `(${left} === ${right})`;
    case "!=": return `(${left} !== ${right})`;
    case "**": return `(${left} ** ${right})`;
    case "%": return `(${left} % ${right})`;
    default: return `(${left} ${op} ${right})`;
  }
}

function emitUnop(op: string, operand: string): string {
  switch (op) {
    case "not": return `(!${operand})`;
    default: return `(${op}${operand})`;
  }
}

function emitCall(fn: string, args: string[]): string {
  const builtins = [
    "len", "str", "push", "print", "println", "head", "tail", "map", "filter", "fold",
    "range", "keys", "values", "type", "abs", "max", "min", "floor", "ceil",
    "round", "sort", "reverse", "contains", "join", "split", "trim", "replace",
    "uppercase", "lowercase", "sum", "flat", "zip", "enumerate", "slice",
    "append", "concat", "unique", "int", "float", "__await", "__fetch_parallel",
    "upper", "lower", "type_of", "__toStr"
  ];
  if (builtins.includes(fn)) {
    return `__arc_runtime.${fn}(${args.join(", ")})`;
  }
  return `${S(fn)}(${args.join(", ")})`;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_$]/g, "_");
}

function S(name: string): string { return sanitizeName(name); }
