// Generated by Arc Compiler

// Arc Runtime
const __arc_runtime = {
  len(a) { return Array.isArray(a) ? a.length : typeof a === "string" ? a.length : 0; },
  str(v) { return String(v); },
  push(arr, v) { arr.push(v); return arr; },
  print(v) { console.log(typeof v === "object" && v !== null ? JSON.stringify(v) : v); },
  head(a) { return a[0]; },
  tail(a) { return a.slice(1); },
  map(a, f) { return a.map(f); },
  filter(a, f) { return a.filter(f); },
  fold(a, init, f) { return a.reduce((acc, x) => f(acc, x), init); },
  range(start, end) { const r = []; for (let i = start; i < end; i++) r.push(i); return r; },
  keys(m) { return m && m.__map ? Array.from(m.entries.keys()) : Object.keys(m || {}); },
  values(m) { return m && m.__map ? Array.from(m.entries.values()) : Object.values(m || {}); },
  type(v) { if (v === null) return "nil"; if (Array.isArray(v)) return "list"; return typeof v; },
  abs(n) { return Math.abs(n); },
  max(a, b) { return Math.max(a, b); },
  min(a, b) { return Math.min(a, b); },
  floor(n) { return Math.floor(n); },
  ceil(n) { return Math.ceil(n); },
  round(n) { return Math.round(n); },
  sort(a) { return [...a].sort((x,y) => x < y ? -1 : x > y ? 1 : 0); },
  reverse(a) { return [...a].reverse(); },
  contains(a, v) { return Array.isArray(a) ? a.includes(v) : typeof a === "string" ? a.includes(v) : false; },
  join(a, sep) { return a.join(sep); },
  split(s, sep) { return s.split(sep); },
  trim(s) { return s.trim(); },
  replace(s, old, nw) { return s.replaceAll(old, nw); },
  uppercase(s) { return s.toUpperCase(); },
  lowercase(s) { return s.toLowerCase(); },
  sum(a) { return a.reduce((s, x) => s + x, 0); },
  flat(a) { return a.flat(); },
  zip(a, b) { return a.map((x, i) => [x, b[i]]); },
  enumerate(a) { return a.map((x, i) => [i, x]); },
  slice(a, s, e) { return a.slice(s, e); },
  append(a, v) { return [...a, v]; },
  concat(a, b) { return [...a, ...b]; },
  unique(a) { return [...new Set(a)]; },
  int(v) { return parseInt(v, 10); },
  float(v) { return parseFloat(v); },
  __await(v) { return v && v.__async ? v.thunk() : v; },
  __fetch_parallel(...targets) { return targets; },
  __make_map(keys, values) { const m = { __map: true, entries: new Map() }; for (let i = 0; i < keys.length; i++) m.entries.set(keys[i], values[i]); return m; },
};

// Main
(function() {
  function classify(x) {
    var __pc = 0;
    __control: while (true) {
      switch (__pc) {
        case 0: /* __start */
          var _0 = null;
          var _1 = x;
          var _2 = 0;
          var _3 = (_1 === _2);
          if (_3) { __pc = 1; } else { __pc = 2; } continue __control;
        case 1: /* match_arm1 */
          var _4 = "zero";
          var __match_result_0 = _4;
          __pc = 6; continue __control;
        case 2: /* match_next2 */
          var _5 = 1;
          var _6 = (_1 === _5);
          if (_6) { __pc = 3; } else { __pc = 4; } continue __control;
        case 3: /* match_arm3 */
          var _7 = "one";
          var __match_result_0 = _7;
          __pc = 6; continue __control;
        case 4: /* match_next4 */
          var _8 = true;
          if (_8) { __pc = 5; } else { __pc = 6; } continue __control;
        case 5: /* match_arm5 */
          var _9 = "other";
          var __match_result_0 = _9;
          __pc = 6; continue __control;
        case 6: /* match_end0 */
          var _10 = __match_result_0;
          return _10;
        default: break __control;
      }
    }
  }

  var classify = classify;
  var _11 = 0;
  var _12 = classify(_11);
  var _13 = __arc_runtime.print(_12);
  var _14 = 1;
  var _15 = classify(_14);
  var _16 = __arc_runtime.print(_15);
  var _17 = 42;
  var _18 = classify(_17);
  var _19 = __arc_runtime.print(_18);
})();
