// Generated by Arc Compiler

// Arc Runtime
const __arc_runtime = {
  len(a) { return Array.isArray(a) ? a.length : typeof a === "string" ? a.length : 0; },
  str(v) { return String(v); },
  push(arr, v) { arr.push(v); return arr; },
  print(v) { console.log(typeof v === "object" && v !== null ? JSON.stringify(v) : v); },
  head(a) { return a[0]; },
  tail(a) { return a.slice(1); },
  map(a, f) { return a.map(f); },
  filter(a, f) { return a.filter(f); },
  fold(a, init, f) { return a.reduce((acc, x) => f(acc, x), init); },
  range(start, end) { const r = []; for (let i = start; i < end; i++) r.push(i); return r; },
  keys(m) { return m && m.__map ? Array.from(m.entries.keys()) : Object.keys(m || {}); },
  values(m) { return m && m.__map ? Array.from(m.entries.values()) : Object.values(m || {}); },
  type(v) { if (v === null) return "nil"; if (Array.isArray(v)) return "list"; return typeof v; },
  abs(n) { return Math.abs(n); },
  max(a, b) { return Math.max(a, b); },
  min(a, b) { return Math.min(a, b); },
  floor(n) { return Math.floor(n); },
  ceil(n) { return Math.ceil(n); },
  round(n) { return Math.round(n); },
  sort(a) { return [...a].sort((x,y) => x < y ? -1 : x > y ? 1 : 0); },
  reverse(a) { return [...a].reverse(); },
  contains(a, v) { return Array.isArray(a) ? a.includes(v) : typeof a === "string" ? a.includes(v) : false; },
  join(a, sep) { return a.join(sep); },
  split(s, sep) { return s.split(sep); },
  trim(s) { return s.trim(); },
  replace(s, old, nw) { return s.replaceAll(old, nw); },
  uppercase(s) { return s.toUpperCase(); },
  lowercase(s) { return s.toLowerCase(); },
  sum(a) { return a.reduce((s, x) => s + x, 0); },
  flat(a) { return a.flat(); },
  zip(a, b) { return a.map((x, i) => [x, b[i]]); },
  enumerate(a) { return a.map((x, i) => [i, x]); },
  slice(a, s, e) { return a.slice(s, e); },
  append(a, v) { return [...a, v]; },
  concat(a, b) { return [...a, ...b]; },
  unique(a) { return [...new Set(a)]; },
  int(v) { return parseInt(v, 10); },
  float(v) { return parseFloat(v); },
  __await(v) { return v && v.__async ? v.thunk() : v; },
  __fetch_parallel(...targets) { return targets; },
  __make_map(keys, values) { const m = { __map: true, entries: new Map() }; for (let i = 0; i < keys.length; i++) m.entries.set(keys[i], values[i]); return m; },
};

// Main
(function() {
  function process(x) {
    var __pc = 0;
    __control: while (true) {
      switch (__pc) {
        case 0: /* __start */
          var _0 = null;
          var _1 = x;
          var _2 = 10;
          var _3 = (_1 > _2);
          if (_3) { __pc = 1; } else { __pc = 2; } continue __control;
        case 1: /* if_then0 */
          var _4 = null;
          var _5 = x;
          var _6 = 2;
          var _7 = (_5 * _6);
          var __if_result_0 = _7;
          __pc = 3; continue __control;
        case 2: /* if_else1 */
          var _8 = null;
          var _9 = x;
          var _10 = 1;
          var _11 = (_9 + _10);
          var __if_result_0 = _11;
          __pc = 3; continue __control;
        case 3: /* if_end2 */
          var _12 = __if_result_0;
          return _12;
        default: break __control;
      }
    }
  }

  function __lambda_3(x) {
    var _16 = x;
    var _17 = 0;
    var _18 = (_16 > _17);
    return _18;
  }

  function __lambda_4(x) {
    var _21 = x;
    var _22 = 2;
    var _23 = (_21 * _22);
    return _23;
  }

  function pipeline_test(items) {
    var _13 = null;
    var _14 = items;
    var _19 = __lambda_3;
    var _15 = __arc_runtime.filter(_14, _19);
    var _24 = __lambda_4;
    var _20 = __arc_runtime.map(_15, _24);
    var _25 = __arc_runtime.sum(_20);
    return _25;
  }

  function match_test(val) {
    var __pc = 0;
    __control: while (true) {
      switch (__pc) {
        case 0: /* __start */
          var _26 = null;
          var _27 = val;
          var _28 = 0;
          var _29 = (_27 === _28);
          if (_29) { __pc = 1; } else { __pc = 2; } continue __control;
        case 1: /* match_arm6 */
          var _30 = "zero";
          var __match_result_5 = _30;
          __pc = 6; continue __control;
        case 2: /* match_next7 */
          var _31 = 1;
          var _32 = (_27 === _31);
          if (_32) { __pc = 3; } else { __pc = 4; } continue __control;
        case 3: /* match_arm8 */
          var _33 = "one";
          var __match_result_5 = _33;
          __pc = 6; continue __control;
        case 4: /* match_next9 */
          var _34 = true;
          if (_34) { __pc = 5; } else { __pc = 6; } continue __control;
        case 5: /* match_arm10 */
          var _35 = "other";
          var __match_result_5 = _35;
          __pc = 6; continue __control;
        case 6: /* match_end5 */
          var _36 = __match_result_5;
          return _36;
        default: break __control;
      }
    }
  }

  var process = process;
  var pipeline_test = pipeline_test;
  var match_test = match_test;
})();
