// ============================================================================
// Mini Compiler in Arc
// ============================================================================
// A compiler for a simple expression language targeting a stack-based VM.
// Includes: lexer, parser, AST, type checker, code generator, optimizer,
// and a virtual machine to execute the generated bytecode.
// The ultimate dogfood — a compiler written in the language itself.
// Demonstrates: regex, pattern matching, closures, pipelines, recursion,
// collections, mut, string interpolation, higher-order functions.
// ============================================================================

import regex
import collections
import math

// ============================================================================
// Part 1: Lexer
// ============================================================================

let TK_INT    = "INT"
let TK_FLOAT  = "FLOAT"
let TK_STRING = "STRING"
let TK_BOOL   = "BOOL"
let TK_IDENT  = "IDENT"
let TK_LET    = "LET"
let TK_MUT    = "MUT"
let TK_FN     = "FN"
let TK_IF     = "IF"
let TK_ELSE   = "ELSE"
let TK_WHILE  = "WHILE"
let TK_RETURN = "RETURN"
let TK_PRINT  = "PRINT"
let TK_PLUS   = "PLUS"
let TK_MINUS  = "MINUS"
let TK_STAR   = "STAR"
let TK_SLASH  = "SLASH"
let TK_MOD    = "MOD"
let TK_EQ     = "EQ"
let TK_NEQ    = "NEQ"
let TK_LT     = "LT"
let TK_GT     = "GT"
let TK_LTE    = "LTE"
let TK_GTE    = "GTE"
let TK_AND    = "AND"
let TK_OR     = "OR"
let TK_NOT    = "NOT"
let TK_ASSIGN = "ASSIGN"
let TK_LPAREN = "LPAREN"
let TK_RPAREN = "RPAREN"
let TK_LBRACE = "LBRACE"
let TK_RBRACE = "RBRACE"
let TK_COMMA  = "COMMA"
let TK_SEMI   = "SEMI"
let TK_ARROW  = "ARROW"
let TK_EOF    = "EOF"

let KEYWORDS = {
    "let": TK_LET, "mut": TK_MUT, "fn": TK_FN,
    "if": TK_IF, "else": TK_ELSE, "while": TK_WHILE,
    "return": TK_RETURN, "print": TK_PRINT,
    "true": TK_BOOL, "false": TK_BOOL,
    "and": TK_AND, "or": TK_OR, "not": TK_NOT
}

let LEX_RULES = [
    { re: regex.compile(r"^\s+"), type: nil },
    { re: regex.compile(r"^//[^\n]*"), type: nil },
    { re: regex.compile(r"^[0-9]+\.[0-9]+"), type: TK_FLOAT },
    { re: regex.compile(r"^[0-9]+"), type: TK_INT },
    { re: regex.compile(r#"^"[^"]*""#), type: TK_STRING },
    { re: regex.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*"), type: TK_IDENT },
    { re: regex.compile(r"^=>"), type: TK_ARROW },
    { re: regex.compile(r"^=="), type: TK_EQ },
    { re: regex.compile(r"^!="), type: TK_NEQ },
    { re: regex.compile(r"^<="), type: TK_LTE },
    { re: regex.compile(r"^>="), type: TK_GTE },
    { re: regex.compile(r"^<"), type: TK_LT },
    { re: regex.compile(r"^>"), type: TK_GT },
    { re: regex.compile(r"^\+"), type: TK_PLUS },
    { re: regex.compile(r"^-"), type: TK_MINUS },
    { re: regex.compile(r"^\*"), type: TK_STAR },
    { re: regex.compile(r"^/"), type: TK_SLASH },
    { re: regex.compile(r"^%"), type: TK_MOD },
    { re: regex.compile(r"^="), type: TK_ASSIGN },
    { re: regex.compile(r"^\("), type: TK_LPAREN },
    { re: regex.compile(r"^\)"), type: TK_RPAREN },
    { re: regex.compile(r"^\{"), type: TK_LBRACE },
    { re: regex.compile(r"^\}"), type: TK_RBRACE },
    { re: regex.compile(r"^,"), type: TK_COMMA },
    { re: regex.compile(r"^;"), type: TK_SEMI }
]

pub fn lex(source) => {
    let mut tokens = []
    let mut pos = 0
    let mut remaining = source
    let mut line = 1
    
    loop {
        match remaining == "" {
            true => break,
            false => {
                let mut matched = false
                LEX_RULES |> collections.each(fn(rule) => {
                    match matched { true => {}, false => {
                        let m = regex.match(rule.re, remaining)
                        match m {
                            nil => {},
                            _ => {
                                matched = true
                                let text = m[0]
                                let len = collections.length(text)
                                
                                // Count newlines
                                line = line + (text |> collections.filter(fn(c) => c == "\n") |> collections.length())
                                
                                match rule.type {
                                    nil => {},
                                    _ => {
                                        let type = match rule.type {
                                            TK_IDENT => collections.get(KEYWORDS, text, TK_IDENT),
                                            _ => rule.type
                                        }
                                        tokens = tokens |> collections.append({ type: type, value: text, line: line })
                                    }
                                }
                                remaining = remaining |> collections.slice(len)
                                pos = pos + len
                            }
                        }
                    }}
                })
                match matched {
                    false => {
                        print("Lexer error at line ${line}: unexpected '${remaining[0]}'")
                        remaining = remaining |> collections.slice(1)
                        pos = pos + 1
                    },
                    true => {}
                }
            }
        }
    }
    
    tokens |> collections.append({ type: TK_EOF, value: "", line: line })
}

// ============================================================================
// Part 2: Parser
// ============================================================================

pub fn parse(tokens) => {
    let mut pos = 0
    
    fn peek() => tokens[pos]
    fn advance() => { let t = tokens[pos]; pos = pos + 1; t }
    fn expect(type) => {
        let t = advance()
        match t.type == type {
            true => t,
            false => { print("Parse error: expected ${type}, got ${t.type} at line ${t.line}"); t }
        }
    }
    fn match_tok(type) => match peek().type == type { true => { advance(); true }, false => false }
    
    fn parse_program() => {
        let mut stmts = []
        loop {
            match peek().type {
                TK_EOF => break,
                _ => stmts = stmts |> collections.append(parse_statement())
            }
        }
        { type: "program", body: stmts }
    }
    
    fn parse_statement() => {
        match peek().type {
            TK_LET => parse_let(),
            TK_FN => parse_fn_decl(),
            TK_IF => parse_if(),
            TK_WHILE => parse_while(),
            TK_RETURN => parse_return(),
            TK_PRINT => parse_print(),
            TK_LBRACE => parse_block(),
            _ => {
                let expr = parse_expression()
                // Check for assignment
                match peek().type {
                    TK_ASSIGN => {
                        advance()
                        let value = parse_expression()
                        match_tok(TK_SEMI)
                        { type: "assign", target: expr, value: value }
                    },
                    _ => { match_tok(TK_SEMI); { type: "expr_stmt", expr: expr } }
                }
            }
        }
    }
    
    fn parse_let() => {
        advance()  // consume 'let'
        let is_mut = match_tok(TK_MUT)
        let name = expect(TK_IDENT).value
        expect(TK_ASSIGN)
        let value = parse_expression()
        match_tok(TK_SEMI)
        { type: "let", name: name, mutable: is_mut, value: value }
    }
    
    fn parse_fn_decl() => {
        advance()  // consume 'fn'
        let name = expect(TK_IDENT).value
        expect(TK_LPAREN)
        let params = parse_param_list()
        expect(TK_RPAREN)
        let body = match peek().type {
            TK_ARROW => { advance(); let e = parse_expression(); match_tok(TK_SEMI); { type: "block", body: [{ type: "return", value: e }] } },
            _ => parse_block()
        }
        { type: "fn_decl", name: name, params: params, body: body }
    }
    
    fn parse_param_list() => {
        let mut params = []
        match peek().type == TK_RPAREN {
            true => params,
            false => {
                params = [expect(TK_IDENT).value]
                loop {
                    match match_tok(TK_COMMA) {
                        true => params = params |> collections.append(expect(TK_IDENT).value),
                        false => break
                    }
                }
                params
            }
        }
    }
    
    fn parse_if() => {
        advance()  // consume 'if'
        let condition = parse_expression()
        let body = parse_block()
        let else_body = match match_tok(TK_ELSE) {
            true => match peek().type {
                TK_IF => parse_if(),
                _ => parse_block()
            },
            false => nil
        }
        { type: "if", condition: condition, body: body, else_body: else_body }
    }
    
    fn parse_while() => {
        advance()
        let condition = parse_expression()
        let body = parse_block()
        { type: "while", condition: condition, body: body }
    }
    
    fn parse_return() => {
        advance()
        let value = match peek().type == TK_SEMI { true => nil, false => parse_expression() }
        match_tok(TK_SEMI)
        { type: "return", value: value }
    }
    
    fn parse_print() => {
        advance()
        let value = parse_expression()
        match_tok(TK_SEMI)
        { type: "print", value: value }
    }
    
    fn parse_block() => {
        expect(TK_LBRACE)
        let mut stmts = []
        loop {
            match peek().type {
                TK_RBRACE => break,
                _ => stmts = stmts |> collections.append(parse_statement())
            }
        }
        expect(TK_RBRACE)
        { type: "block", body: stmts }
    }
    
    fn parse_expression() => parse_or()
    
    fn parse_or() => {
        let mut left = parse_and()
        loop {
            match peek().type {
                TK_OR => { advance(); left = { type: "binop", op: "or", left: left, right: parse_and() } },
                _ => break
            }
        }
        left
    }
    
    fn parse_and() => {
        let mut left = parse_comparison()
        loop {
            match peek().type {
                TK_AND => { advance(); left = { type: "binop", op: "and", left: left, right: parse_comparison() } },
                _ => break
            }
        }
        left
    }
    
    fn parse_comparison() => {
        let mut left = parse_additive()
        let op = match peek().type {
            TK_EQ => "==", TK_NEQ => "!=", TK_LT => "<", TK_GT => ">",
            TK_LTE => "<=", TK_GTE => ">=", _ => nil
        }
        match op {
            nil => left,
            _ => { advance(); { type: "binop", op: op, left: left, right: parse_additive() } }
        }
    }
    
    fn parse_additive() => {
        let mut left = parse_multiplicative()
        loop {
            match peek().type {
                TK_PLUS => { advance(); left = { type: "binop", op: "+", left: left, right: parse_multiplicative() } },
                TK_MINUS => { advance(); left = { type: "binop", op: "-", left: left, right: parse_multiplicative() } },
                _ => break
            }
        }
        left
    }
    
    fn parse_multiplicative() => {
        let mut left = parse_unary()
        loop {
            match peek().type {
                TK_STAR => { advance(); left = { type: "binop", op: "*", left: left, right: parse_unary() } },
                TK_SLASH => { advance(); left = { type: "binop", op: "/", left: left, right: parse_unary() } },
                TK_MOD => { advance(); left = { type: "binop", op: "%", left: left, right: parse_unary() } },
                _ => break
            }
        }
        left
    }
    
    fn parse_unary() => {
        match peek().type {
            TK_MINUS => { advance(); { type: "unary", op: "-", operand: parse_unary() } },
            TK_NOT => { advance(); { type: "unary", op: "not", operand: parse_unary() } },
            _ => parse_primary()
        }
    }
    
    fn parse_primary() => {
        match peek().type {
            TK_INT => { let t = advance(); { type: "int_lit", value: t.value |> to_number() } },
            TK_FLOAT => { let t = advance(); { type: "float_lit", value: t.value |> to_number() } },
            TK_STRING => { let t = advance(); { type: "string_lit", value: t.value |> collections.slice(1, -1) } },
            TK_BOOL => { let t = advance(); { type: "bool_lit", value: t.value == "true" } },
            TK_IDENT => {
                let t = advance()
                match peek().type {
                    TK_LPAREN => {
                        advance()
                        let args = parse_arg_list()
                        expect(TK_RPAREN)
                        { type: "call", name: t.value, args: args }
                    },
                    _ => { type: "ident", name: t.value }
                }
            },
            TK_LPAREN => { advance(); let e = parse_expression(); expect(TK_RPAREN); e },
            _ => { print("Unexpected token: ${peek().type}"); advance(); { type: "int_lit", value: 0 } }
        }
    }
    
    fn parse_arg_list() => {
        let mut args = []
        match peek().type == TK_RPAREN {
            true => args,
            false => {
                args = [parse_expression()]
                loop {
                    match match_tok(TK_COMMA) {
                        true => args = args |> collections.append(parse_expression()),
                        false => break
                    }
                }
                args
            }
        }
    }
    
    parse_program()
}

// ============================================================================
// Part 3: Code Generator (targeting stack VM)
// ============================================================================

// Bytecode instructions
let OP_PUSH    = "PUSH"
let OP_POP     = "POP"
let OP_ADD     = "ADD"
let OP_SUB     = "SUB"
let OP_MUL     = "MUL"
let OP_DIV     = "DIV"
let OP_MOD     = "MOD"
let OP_NEG     = "NEG"
let OP_NOT     = "NOT"
let OP_EQ      = "EQ"
let OP_NEQ     = "NEQ"
let OP_LT      = "LT"
let OP_GT      = "GT"
let OP_LTE     = "LTE"
let OP_GTE     = "GTE"
let OP_AND     = "AND"
let OP_OR      = "OR"
let OP_LOAD    = "LOAD"
let OP_STORE   = "STORE"
let OP_JMP     = "JMP"
let OP_JZ      = "JZ"
let OP_CALL    = "CALL"
let OP_RET     = "RET"
let OP_PRINT   = "PRINT"
let OP_HALT    = "HALT"

pub fn codegen(ast) => {
    let mut code = []
    let mut functions = {}
    
    fn emit(op, arg) => {
        code = code |> collections.append({ op: op, arg: arg })
    }
    
    fn current_addr() => collections.length(code)
    
    fn patch(addr, new_arg) => {
        code = code |> collections.map_indexed(fn(instr, i) => {
            match i == addr { true => { op: instr.op, arg: new_arg }, false => instr }
        })
    }
    
    fn gen_node(node) => {
        match node {
            { type: "program", body: stmts } => {
                stmts |> collections.each(gen_node)
                emit(OP_HALT, nil)
            },
            { type: "int_lit", value: v } => emit(OP_PUSH, v),
            { type: "float_lit", value: v } => emit(OP_PUSH, v),
            { type: "string_lit", value: v } => emit(OP_PUSH, v),
            { type: "bool_lit", value: v } => emit(OP_PUSH, v),
            { type: "ident", name: n } => emit(OP_LOAD, n),
            
            { type: "binop", op: op, left: l, right: r } => {
                gen_node(l)
                gen_node(r)
                match op {
                    "+" => emit(OP_ADD, nil),
                    "-" => emit(OP_SUB, nil),
                    "*" => emit(OP_MUL, nil),
                    "/" => emit(OP_DIV, nil),
                    "%" => emit(OP_MOD, nil),
                    "==" => emit(OP_EQ, nil),
                    "!=" => emit(OP_NEQ, nil),
                    "<" => emit(OP_LT, nil),
                    ">" => emit(OP_GT, nil),
                    "<=" => emit(OP_LTE, nil),
                    ">=" => emit(OP_GTE, nil),
                    "and" => emit(OP_AND, nil),
                    "or" => emit(OP_OR, nil),
                    _ => {}
                }
            },
            
            { type: "unary", op: "-", operand: o } => { gen_node(o); emit(OP_NEG, nil) },
            { type: "unary", op: "not", operand: o } => { gen_node(o); emit(OP_NOT, nil) },
            
            { type: "let", name: n, value: v } => {
                gen_node(v)
                emit(OP_STORE, n)
            },
            
            { type: "assign", target: t, value: v } => {
                gen_node(v)
                emit(OP_STORE, t.name)
            },
            
            { type: "if", condition: c, body: b, else_body: eb } => {
                gen_node(c)
                let jz_addr = current_addr()
                emit(OP_JZ, 0)  // placeholder
                gen_node(b)
                match eb {
                    nil => patch(jz_addr, current_addr()),
                    _ => {
                        let jmp_addr = current_addr()
                        emit(OP_JMP, 0)
                        patch(jz_addr, current_addr())
                        gen_node(eb)
                        patch(jmp_addr, current_addr())
                    }
                }
            },
            
            { type: "while", condition: c, body: b } => {
                let loop_start = current_addr()
                gen_node(c)
                let jz_addr = current_addr()
                emit(OP_JZ, 0)
                gen_node(b)
                emit(OP_JMP, loop_start)
                patch(jz_addr, current_addr())
            },
            
            { type: "fn_decl", name: n, params: p, body: b } => {
                let jmp_addr = current_addr()
                emit(OP_JMP, 0)
                functions = collections.set(functions, n, { addr: current_addr(), params: p })
                gen_node(b)
                emit(OP_RET, nil)
                patch(jmp_addr, current_addr())
            },
            
            { type: "call", name: n, args: a } => {
                a |> collections.each(gen_node)
                emit(OP_CALL, { name: n, argc: collections.length(a) })
            },
            
            { type: "return", value: v } => {
                match v { nil => emit(OP_PUSH, nil), _ => gen_node(v) }
                emit(OP_RET, nil)
            },
            
            { type: "print", value: v } => {
                gen_node(v)
                emit(OP_PRINT, nil)
            },
            
            { type: "block", body: stmts } => stmts |> collections.each(gen_node),
            { type: "expr_stmt", expr: e } => { gen_node(e); emit(OP_POP, nil) },
            
            _ => print("Codegen: unknown node type: ${node.type}")
        }
    }
    
    gen_node(ast)
    { code: code, functions: functions }
}

// ============================================================================
// Part 4: Virtual Machine
// ============================================================================

pub fn create_vm(program) => {
    {
        code: program.code,
        functions: program.functions,
        ip: 0,
        stack: [],
        call_stack: [],
        env: {},
        output: [],
        halted: false
    }
}

pub fn run(vm) => {
    let mut v = vm
    let mut steps = 0
    let max_steps = 100000
    
    loop {
        match v.halted or v.ip >= collections.length(v.code) or steps >= max_steps {
            true => break,
            false => {
                let instr = v.code[v.ip]
                v.ip = v.ip + 1
                steps = steps + 1
                
                v = execute_instruction(v, instr)
            }
        }
    }
    
    match steps >= max_steps {
        true => print("VM: max steps reached (infinite loop?)"),
        false => {}
    }
    
    v
}

fn execute_instruction(vm, instr) => {
    let mut v = vm
    
    match instr.op {
        OP_PUSH => { v.stack = v.stack |> collections.append(instr.arg) },
        OP_POP => { v.stack = v.stack |> collections.drop_last(1) },
        
        OP_ADD => { let [a, b] = pop2(v); v.stack = push(v.stack, a + b) },
        OP_SUB => { let [a, b] = pop2(v); v.stack = push(v.stack, a - b) },
        OP_MUL => { let [a, b] = pop2(v); v.stack = push(v.stack, a * b) },
        OP_DIV => { let [a, b] = pop2(v); v.stack = push(v.stack, a / b) },
        OP_MOD => { let [a, b] = pop2(v); v.stack = push(v.stack, a % b) },
        OP_NEG => { let a = pop1(v); v.stack = push(v.stack, -a) },
        OP_NOT => { let a = pop1(v); v.stack = push(v.stack, !a) },
        
        OP_EQ  => { let [a, b] = pop2(v); v.stack = push(v.stack, a == b) },
        OP_NEQ => { let [a, b] = pop2(v); v.stack = push(v.stack, a != b) },
        OP_LT  => { let [a, b] = pop2(v); v.stack = push(v.stack, a < b) },
        OP_GT  => { let [a, b] = pop2(v); v.stack = push(v.stack, a > b) },
        OP_LTE => { let [a, b] = pop2(v); v.stack = push(v.stack, a <= b) },
        OP_GTE => { let [a, b] = pop2(v); v.stack = push(v.stack, a >= b) },
        OP_AND => { let [a, b] = pop2(v); v.stack = push(v.stack, a and b) },
        OP_OR  => { let [a, b] = pop2(v); v.stack = push(v.stack, a or b) },
        
        OP_LOAD => { v.stack = push(v.stack, collections.get(v.env, instr.arg, nil)) },
        OP_STORE => {
            let val = pop1(v)
            v.env = collections.set(v.env, instr.arg, val)
        },
        
        OP_JMP => { v.ip = instr.arg },
        OP_JZ => {
            let val = pop1(v)
            match !val { true => v.ip = instr.arg, false => {} }
        },
        
        OP_CALL => {
            let fn_info = collections.get(v.functions, instr.arg.name, nil)
            match fn_info {
                nil => print("VM: undefined function '${instr.arg.name}'"),
                _ => {
                    // Save state
                    v.call_stack = v.call_stack |> collections.append({
                        return_addr: v.ip,
                        saved_env: v.env
                    })
                    // Bind params
                    let argc = instr.arg.argc
                    let args = v.stack |> collections.take_last(argc)
                    v.stack = v.stack |> collections.drop_last(argc)
                    fn_info.params |> collections.each_indexed(fn(param, i) => {
                        v.env = collections.set(v.env, param, args[i])
                    })
                    v.ip = fn_info.addr
                }
            }
        },
        
        OP_RET => {
            match collections.length(v.call_stack) > 0 {
                true => {
                    let frame = v.call_stack |> collections.last()
                    v.call_stack = v.call_stack |> collections.drop_last(1)
                    let ret_val = match collections.length(v.stack) > 0 {
                        true => pop1(v),
                        false => nil
                    }
                    v.env = frame.saved_env
                    v.ip = frame.return_addr
                    match ret_val != nil {
                        true => v.stack = push(v.stack, ret_val),
                        false => {}
                    }
                },
                false => v.halted = true
            }
        },
        
        OP_PRINT => {
            let val = pop1(v)
            v.output = v.output |> collections.append("${val}")
            print("  > ${val}")
        },
        
        OP_HALT => { v.halted = true },
        
        _ => print("VM: unknown opcode '${instr.op}'")
    }
    
    v
}

fn pop1(vm) => {
    let val = vm.stack |> collections.last()
    vm.stack = vm.stack |> collections.drop_last(1)
    val
}

fn pop2(vm) => {
    let b = pop1(vm)
    let a = pop1(vm)
    [a, b]
}

fn push(stack, val) => stack |> collections.append(val)

// ============================================================================
// Part 5: Disassembler (for debugging)
// ============================================================================

pub fn disassemble(program) => {
    print("\n--- Bytecode ---")
    program.code |> collections.each_indexed(fn(instr, i) => {
        let addr = "${i}" |> pad_left(4, "0")
        let arg_str = match instr.arg {
            nil => "",
            { name: n, argc: a } => "${n}(${a})",
            _ => "${instr.arg}"
        }
        print("  ${addr}: ${instr.op} ${arg_str}")
    })
    
    print("\nFunctions:")
    program.functions |> collections.entries() |> collections.each(fn(e) => {
        print("  ${e.key}(${e.value.params |> collections.join(", ")}) @ ${e.value.addr}")
    })
}

// ============================================================================
// Part 6: Full Pipeline
// ============================================================================

pub fn compile(source) => {
    print("--- Compiling ---")
    let tokens = lex(source)
    print("Lexed: ${collections.length(tokens)} tokens")
    
    let ast = parse(tokens)
    print("Parsed: ${ast.body |> collections.length()} top-level statements")
    
    let program = codegen(ast)
    print("Generated: ${collections.length(program.code)} instructions")
    
    program
}

pub fn compile_and_run(source) => {
    let program = compile(source)
    disassemble(program)
    
    print("\n--- Running ---")
    let vm = create_vm(program) |> run()
    
    print("\n--- Result ---")
    print("Output: ${vm.output |> collections.join(", ")}")
    print("Final stack: ${vm.stack}")
    vm
}

// --- Main Demo ---

fn main() => {
    print("=== Arc Compiler Demo ===\n")
    
    // Program 1: Fibonacci
    print("========== Fibonacci ==========")
    compile_and_run("
        fn fib(n) {
            if n <= 1 {
                return n;
            }
            return fib(n - 1) + fib(n - 2);
        }
        
        let mut i = 0;
        while i < 10 {
            print fib(i);
            i = i + 1;
        }
    ")
    
    // Program 2: Factorial
    print("\n========== Factorial ==========")
    compile_and_run("
        fn factorial(n) {
            if n <= 1 {
                return 1;
            }
            return n * factorial(n - 1);
        }
        
        print factorial(5);
        print factorial(10);
    ")
    
    // Program 3: FizzBuzz
    print("\n========== FizzBuzz ==========")
    compile_and_run("
        let mut i = 1;
        while i <= 20 {
            if i % 15 == 0 {
                print \"FizzBuzz\";
            } else {
                if i % 3 == 0 {
                    print \"Fizz\";
                } else {
                    if i % 5 == 0 {
                        print \"Buzz\";
                    } else {
                        print i;
                    }
                }
            }
            i = i + 1;
        }
    ")
    
    // Program 4: Simple math
    print("\n========== Math Expressions ==========")
    compile_and_run("
        let x = 10;
        let y = 3;
        print x + y * 2;
        print (x + y) * 2;
        print x % y;
        print -x + 15;
        print x > y and y > 0;
        print not false;
    ")
    
    print("\nCompiler demo complete!")
}

main()
